---
# tasks file for ansible-role-dell

- name: Add channel gpg keys
  copy:
    src: "RPM-GPG-KEY-dell"
    dest: '/etc/pki/rpm-gpg/RPM-GPG-KEY-dell'

- name: Import channel gpg keys
  rpm_key:
    state: present
    key: '/etc/pki/rpm-gpg/RPM-GPG-KEY-dell'

- name: Subscribe to required channels
  rhn_channel:
    name: '{{ item }}'
    state: '{{ item.state | default("present") }}'
    sysname: '{{ inventory_hostname }}'
    url: 'https://{{ spacewalk_server }}/rpc/api'
    user: '{{ spacewalk_admin_user }}'
    password: '{{ spacewalk_admin_password }}'
  with_items:
    - '{{ dell_rhn_channels }}'

- name: install packages
  yum: pkg={{ item }}
  with_items: "{{ dell_packages }}"
  when: dell_packages.0 != ""

- name: install omreport packages
  yum: pkg={{ item }}
  with_items: "{{ dell_omreport_packages }}"
  when: dell_omreport_packageges.0 != "" and dell_omreport
  register: reg_installed_omreport

- name: restart dell services if we just installed them
  command: /opt/dell/srvadmin/sbin/srvadmin-services.sh restart
  when: reg_installed_omreport.changed

- name: copy in idrac csc helper scripts
  copy: src={{ item }} dest=/usr/local/bin/{{ item }} mode=0755 owner=root group=root backup=no
  with_items: "{{ dell_helper_scripts }}"
  when: dell_helper_scripts.0 != "" and dell_install_helper_scripts

- name: copy remote console app binary
  copy: src=remoteConsoleLoader dest=/opt/dell/remoteConsoleLoader mode=0755 owner=root group=root backup=no

- name: disable NVMe device monitoring - in OMSA 8.3 it breaks omreport commands
  lineinfile: dest=/opt/dell/srvadmin/etc/srvadmin-storage/stsvc.ini
              line="; vil7=dsm_sm_psrvil" 
              backup=yes 
              regexp="^.*vil7=dsm_sm_psrvil$"
  notify:
   - restart_dell_services
  when: dell_disable_vil7

- name: install check_openmanage
  yum:
    name: nagios-plugins-openmanage
    state: installed
  tags:
    - monitoring

- name: copy nrpe check definition
  template:
    src: check_openmanage.cfg.j2
    dest: /etc/nrpe.d/check_openmanage.cfg
    owner: nrpe
    group: nrpe
    mode: 0644
  notify: restart nrpe
  tags:
    - monitoring


