---
# tasks file for ansible-role-dell

 - name: add Dell DSU repo
   template: src=dell-system-update-repository.repo.j2 dest=/etc/yum.repos.d/dell-system-update-repository.repo mode=0644 owner=root backup=yes

 - name: install Dell DSU Key
   rpm_key: key=http://linux.dell.com/repo/hardware/dsu/public.key state=present

 - name: install packages
   yum:
     name: "{{ dell_packages }}"
   when: dell_packages.0 != ""

 - name: install omreport packages
   yum:
     name: "{{ dell_omreport_packages }}"
   when: dell_omreport_packages.0 != "" and dell_omreport
   register: reg_installed_omreport

 - name: restart dell services if we just installed them
   command: /opt/dell/srvadmin/sbin/srvadmin-services.sh restart
   when: reg_installed_omreport.changed

 - name: copy in idrac csc helper scripts
   copy: src={{ item }} dest=/usr/local/bin/{{ item }} mode=0755 owner=root group=root backup=no
   with_items: "{{ dell_helper_scripts }}"
   when: dell_helper_scripts.0 != "" and dell_install_helper_scripts

 - name: copy remote console app binary
   copy: src=remoteConsoleLoader dest=/opt/dell/remoteConsoleLoader mode=0755 owner=root group=root backup=no

 - name: disable NVMe device monitoring - in OMSA 8.3 it breaks omreport commands
   lineinfile: dest=/opt/dell/srvadmin/etc/srvadmin-storage/stsvc.ini
               line="; vil7=dsm_sm_psrvil" 
               backup=yes 
               regexp="^.*vil7=dsm_sm_psrvil$"
   notify:
    - restart_dell_services
   when: dell_disable_vil7
